components/HomePage/Activities.tsx, components/HomePage/ApplicationForm.tsx, components/HomePage/Banner.tsx, components/HomePage/Introduction.tsx, components/HomePage/Speakers.tsx, components/HomePage/SponsorsAndOrganizers.tsx, components/HomePage/Venue.tsx, components/Layout/Header.tsx, public/constant/content.ts, public/constant/urls.ts
- Update styles
- Update contents
- Disable buttons
=> Update styles and contents

components/FAQPage/FAQ.tsx, components/Layout/Header.tsx, components/VisaPage/Visa.tsx, pages/faq/index.tsx, public/constant/content.ts, public/constant/urls.ts
=> Add faq page

pages/_document.tsx
Add locks on Arbitrum & Polygon
=> build: Add locks on Arbitrum & Polygon

components/AgendaPage/Agendas.tsx, public/constant/agendas.ts, public/constant/content.ts
=> feat: add conference agenda

public/constant/agendas.ts
=> chore: fix name

components/FAQPage/FAQ.tsx, public/constant/content.ts, public/constant/urls.ts
=> feat: add side event form in faq

components/AgendaPage/Agendas.tsx
=> Bring something in!

public/constant/agendas.ts
=> chore: switch speaker session

public/constant/agendas.ts, public/constant/organizers.ts
=> Chore: fix typo and update agenda

components/AgendaPage/Agendas.tsx, public/constant/agendas.ts
=> chore: add organizations of security panel

public/constant/sponsors.ts, public/constant/urls.ts
=> chore: remove zksync

components/HomePage/Banner.tsx, public/constant/urls.ts
=> feat: add notification

public/constant/agendas.ts
=> chore: update agenda

public/constant/content.ts, public/constant/urls.ts
=> feat: update content

components/AgendaPage/Agendas.tsx, public/constant/agendas.ts
=> feat: add workshops

components/AgendaPage/Agendas.tsx, public/constant/agendas.ts
=> chore: update derivative panel attendees

components/AgendaPage/Agendas.tsx, public/constant/agendas.ts
=> feat: add conference workshops

public/constant/agendas.ts
=> feat: update Hsiao-Wei's topic

components/HomePage/ApplicationForm.tsx, components/HomePage/Speakers.tsx, public/constant/content.ts, public/constant/urls.ts
* Add link to application form
* Add 3 photos of previous speakers so the section looks less boring
=> feat: link to application form

components/HomePage/Banner.tsx, components/Layout/Header.tsx, public/constant/content.ts, public/constant/urls.ts
=> feat: add watermark 2023 and add link to ETHTaipei2024 site

components/HomePage/ApplicationForm.tsx, components/HomePage/Banner.tsx, components/HomePage/Speakers.tsx, public/constant/content.ts
What I did
- Fix https://github.com/ETHTaipei/ETH-Taipei-Website/issues/185
- 更新首頁一些內容
=> Add speaker vitalik

components/HomePage/Banner.tsx, public/constant/content.ts, public/constant/urls.ts
close https://github.com/ETHTaipei/ETH-Taipei-Website/issues/196
=> feat: add apply side event button to banner

components/HomePage/Activities.tsx, components/HomePage/Banner.tsx, public/constant/content.ts, public/constant/urls.ts
=> Update conf and hackathon links

components/FAQPage/FAQ.tsx, components/HomePage/Banner.tsx, public/constant/content.ts, public/constant/urls.ts
close https://github.com/ETHTaipei/ETH-Taipei-Website/issues/204
=> feat: add invitation link

components/New/HomePage/Activities.tsx, components/New/HomePage/Recap.tsx, components/New/HomePage/Sponsors.tsx, components/hooks/useSponsors.tsx, pages/new/index.tsx, public/constant/content.ts
* Also update ticket sales button
=> feat: new sponsor section

components/New/HomePage/FloatingBotton.tsx, pages/new/index.tsx
=> feat: floating button

components/New/HomePage/Sponsors.tsx
Need it now after adding gold tier sponsors
=> ui: margin between description & sponsors

components/FAQPage/FAQ.tsx, public/constant/content.ts
1. 更新 FAQ Page Style
2. 更新 Title 為 "Infos"。原因是：1. 這個頁面目前只有 Visa 資訊 2. 讓這個頁面可以放更多資訊 e.g. 贊助商想曝光的資訊。另外也參考 EthCC 的 [Infos Page](https://ethcc.io/infos)
新版
舊版
=> Fix faq page

components/New/HomePage/Banner.tsx, components/New/HomePage/CountdownTimer/CountdownCard.tsx, components/New/HomePage/CountdownTimer/index.tsx, components/hooks/useCountdownTime.ts
close https://github.com/ETHTaipei/ETH-Taipei-Website/issues/216
=> feat: add countdown timer

components/AgendaPage/ConferenceTable.tsx, components/AgendaPage/VitalikTable.tsx, components/AgendaPage/WorkshopItem.tsx, components/AgendaPage/ui/SpeakerInfo.tsx, public/constant/agendas.ts
close https://github.com/ETHTaipei/ETH-Taipei-Website/issues/261
close https://github.com/ETHTaipei/ETH-Taipei-Website/issues/259
=> Increase agenda speaker info size & Update agenda content

components/AgendaPage/VitalikTable.tsx, public/constant/agendas.ts
* Vitalik's presence should not be marked as virtual
* adding title to Martinet's talk
* Change the name of Defi panel
=> Agenda Minor Fix

components/AgendaPage/ConferenceItem.tsx, components/AgendaPage/VitalikTable.tsx, components/AgendaPage/ui/PanelInfo.tsx, public/constant/agendas.ts
close https://github.com/ETHTaipei/ETH-Taipei-Website/issues/267
=> feat: add agenda panel info ui

components/AgendaPage/Agendas.tsx, components/AgendaPage/EventSwitcher.tsx, components/AgendaPage/SideEventItem.tsx, components/AgendaPage/SideEventTable.tsx, components/AgendaPage/ui/HeaderCell.tsx, public/constant/agendas.ts
=> feat: add side event

components/AgendaPage/EventSwitcher.tsx, components/AgendaPage/SideEventTable.tsx, public/constant/agendas.ts
Update side event's name to In-house event. Haven't figured ways to link to the side event spreadsheet, but this should create less possibility.
=> agenda update

components/AgendaPage/EventSwitcher.tsx, public/constant/content.ts
=> chore: update 2024 conf date

components/New/HomePage/Contributors.tsx, components/New/HomePage/Organizers.tsx
- fixed avatars being cropped md size
=> fix: avatar display issue
